sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shachardron/docker-reactnew -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-reactnew npm run test
